notes: |
  # Initialization

  ```javascript
  window.addEventListener('DOMContentLoaded', function() {
    var el = document.querySelector('#my-contact-form');
    new Styleguide.ContactForm(el);
  });
  ```
variants:
  - name: personal
