notes: |
  Background is transparent, ensure a good contrast with the background or use an alternate version.

  # Make it shrink !

  In case you use the sticky navbar, you should make it shrink while the user scroll to free-up some space. To do so, use the following code:

  ```javascript
  window.addEventListener('DOMContentLoaded', function() {
    var navbar = document.querySelector('#my-sticky-navbar');
    new Toolkit.Navbar(navbar, { mode: 'window' });
  });
  ```

  There is two modes available: `window` and `instant`, the latter being by default. `instant` make it shrink as soon as the user scroll. `window` start the transition when the end of the first screen approach the top, corresponding to the beginning of the second fitted section. You can see example of implementation in the <a href="/example-pages.html">example pages</a>.
variants:
  - name: negative
    notes: Inverse the colors to use on a dark background
    context:
      modifier: navbar--negative
    display:
      background-color: "#414141"
  - name: sticky
    notes: Make it stick to the top of the window
    context:
      modifier: navbar--sticky
  - name: plain
    notes: Add a sligthly transparent light background
    context:
      modifier: navbar--plain
  - name: overlay
    notes: Add a light background
    context:
      modifier: navbar--overlay
  - name: secondary
    notes: To be used in subpages where the main navigation is not desired. Back button text should describe the page it links to, for example "Back to team".
  - name: expertise
    notes: A custom navbar dedicated to the expertise pages.
