notes: |
  Create a reel of aligned items where their size is more or less distributed fairly. When there’s more items than the available space, the user is able to swipe horizontaly or use the buttons to navigate.

  ## Initialization

  ```javascript
  window.addEventListener('DOMContentLoaded', function() {
    var reel = document.querySelector('#reel');
    new Toolkit.Reel(reel);
  });
  ```

  ## Methods

  <table class="table">
    <tbody>
      <tr>
        <td width="20%"><code>reel.refresh()</code></td>
        <td>Recalculate dimensions and display navigation accordingly.</td>
      </tr>
      <tr>
        <td width="20%"><code>reel.destroy()</code></td>
        <td>Destroy the component, stop listening for events.</td>
      </tr>
    </tbody>
  </table>
