context:
  brands:
    - image: '/assets/images/logos/freitag.svg'
      alt: 'Freitag'
    - image: '/assets/images/logos/migros.svg'
      alt: 'Migros'
    - image: '/assets/images/logos/angular.svg'
      alt: 'Angular'
    - image: '/assets/images/logos/opendata.svg'
      alt: 'OpenData.swiss'
    - image: '/assets/images/logos/react.svg'
      alt: 'React.js'
    - image: '/assets/images/logos/postfinance.svg'
      alt: 'PostFinance'
    - image: '/assets/images/logos/vue.svg'
      alt: 'Vue.js'
    - image: '/assets/images/logos/sbb.svg'
      alt: 'SBB CFF FFS'
    - image: '/assets/images/logos/swisscom.svg'
      alt: 'Swisscom'
