notes: |
  Partially hide detailed content inside collapsed containers. Both title and navigation can be used to show the associated content. A playground can lives between the list and the navigation for illustration purpose. Both playground and navigation are optional.

  On large screens, the accordion height is fixed to the height it would be when the biggest element is open. This prevent the content from wiggling during transitions.

  Use the `data-current` attribute on the `.accordion` element if you want to change the playground state depending on the element currently open.

  ⚠️  The playground animation shown in here act as an example and is not part of the styleguide.

  ## Initialization

  ```javascript
  window.addEventListener('DOMContentLoaded', function() {
    var el = document.querySelector('#my-accordion');
    new Toolkit.Accordion(el);
  });
  ```

  ## Methods

  <table class="table">
    <tbody>
      <tr>
        <td width="20%"><code>accordion.destroy()</code></td>
        <td>Destroy the accordion object, remove all event listeners.</td>
      </tr>
    </tbody>
  </table>
