context:
  icons:
    Brand:
      - logo
      - slashes
    Expertises:
      - agile-teams
      - analytics
      - api
      - audit
      - content
      - content-management
      - custom-development
      - data-science
      - design-thinking
      - ecommerce
      - elearning
      - fintech
      - mobile
      - open-source
      - prototyping
      - sea
      - seo
      - service-design
      - teal-agile
      - user-experience
      - ux-design
    Social:
      - facebook
      - github
      - instagram
      - linkedin
      - rss
      - twitter
    Miscellaneous:
      - caret
      - chevron-alt-right
      - chevron-down
      - chevron-left
      - chevron-right
      - chevron-up
      - close
      - paper-plane
