notes: Portrays a Liip expertise. It should always link to the corresponding expertise page.
display:
  max-width: 300px
context:
  icon: ecommerce
  name: E-commerce
  teaser: Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam, commodi excepturi? Eius, voluptates quia dolorem obcaecat.
